name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base UI
  cupertino_icons: ^1.0.8

  # Estado + i18n + utils
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.7+1

  # Mapas y backend
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  http: ^1.2.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  socket_io_client: ^3.1.4

  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  permission_handler: ^11.1.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.0

  # Animaciones y efectos visuales
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/legal/
    - assets/animations/
    - assets/icons/
